apiVersion: v1
kind: Service
metadata:
  name: overauthattacker
  labels:
    app: overauthattacker
spec:
  ports:
    - port: 9080
      name: http
      targetPort: 9080
  selector:
    app: overauthattacker
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: overauthattacker-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: overauthattacker
        version: v1
    spec:
      containers:
      - name: overauthattacker
        image: overauthattacker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 25
        - containerPort: 587